import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { supabaseAdmin } from "@/integrations/supabase/client.server";

async function requireRhOperator(context: { userId: string }) {
  const { data, error } = await supabaseAdmin.from("users").select("id,username,status,role_key").eq("auth_id", context.userId).maybeSingle();
  if (error || !data || data.status !== "ativo") throw new Error("Usuário sem acesso ao RH.");
  const allowed = ["SUPER_ADMIN","ADMIN_OPERACIONAL","GESTOR_CONTA","GESTOR_REGIONAL"];
  if (!allowed.includes(data.role_key ?? "") && !["DBS123","DBSASSISTENCIA123"].includes(data.username ?? "")) throw new Error("Acesso restrito à gestão do RH.");
  return data;
}
const moneyToCents=(value:unknown)=>{const raw=String(value??"").trim();if(!raw)return 0;const n=Number(raw.replace(/[^0-9,.-]/g,"").replace(/\./g,"").replace(",","."));return Number.isFinite(n)?Math.round(n*100):0;};

export const getRhManagementDashboard=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{
  await requireRhOperator(context);
  const [employees,docs,vacations,vacationRequests,payroll,admissions,exams,requests]=await Promise.all([
    supabaseAdmin.from("rh_employees").select("id,full_name,unit,is_active,registration_data").order("full_name"),
    supabaseAdmin.from("rh_employee_documents").select("id,employee_id,document_type,file_name,expires_at,status").order("expires_at"),
    supabaseAdmin.from("rh_vacation_periods").select("id,employee_id,concession_deadline,status,days_earned,days_used").order("concession_deadline"),
    supabaseAdmin.from("rh_vacation_requests").select("id,employee_id,start_date,end_date,days,status,requested_at").order("start_date",{ascending:false}).limit(30),
    supabaseAdmin.from("rh_payroll_periods").select("id,competence,status").order("competence",{ascending:false}).limit(12),
    supabaseAdmin.from("rh_admission_processes").select("id,employee_id,status,expected_start").order("expected_start"),
    supabaseAdmin.from("rh_medical_exams").select("id,employee_id,exam_type,valid_until,result").order("valid_until"),
    supabaseAdmin.from("rh_employee_requests").select("id,employee_id,request_type,status,requested_at").order("requested_at",{ascending:false}).limit(20)
  ]);
  for(const r of [employees,docs,vacations,vacationRequests,payroll,admissions,exams,requests])if(r.error)throw new Error(r.error.message);
  const now=Date.now();const soon=(d:string|null|undefined,days:number)=>{if(!d)return false;const t=new Date(d+"T12:00:00").getTime();return t>=now&&t<=now+days*86400000;};
  return {employees:(employees.data??[]).filter((e:any)=>e.is_active).length,inactive:(employees.data??[]).filter((e:any)=>!e.is_active).length,documentsExpiring:(docs.data??[]).filter((d:any)=>d.status!=="inativo"&&soon(d.expires_at,30)).length,vacationsDue:(vacations.data??[]).filter((v:any)=>v.status==="aberto"&&soon(v.concession_deadline,60)).length,payrollOpen:(payroll.data??[]).filter((p:any)=>p.status!=="fechada").length,admissionsPending:(admissions.data??[]).filter((a:any)=>a.status!=="concluida").length,examsExpiring:(exams.data??[]).filter((e:any)=>soon(e.valid_until,30)).length,requestsOpen:(requests.data??[]).filter((r:any)=>!["resolvida","cancelada"].includes(r.status)).length,employeesData:employees.data??[],documents:docs.data??[],vacations:vacations.data??[],vacationRequests:vacationRequests.data??[],payroll:payroll.data??[],admissions:admissions.data??[],exams:exams.data??[],requests:requests.data??[]};
});

export const createRhPayrollPeriod=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:{competence:string})=>{if(!input?.competence)throw new Error("Informe a competência.");return input;}).handler(async({context,data})=>{
  const actor=await requireRhOperator(context);const competence=data.competence.length===7?data.competence+"-01":data.competence;
  const {data:existing,error:xe}=await supabaseAdmin.from("rh_payroll_periods").select("*").eq("competence",competence).maybeSingle();if(xe)throw new Error(xe.message);if(existing?.status==="fechada")throw new Error("Esta competência já está fechada e não pode ser reaberta.");const period=existing??(await supabaseAdmin.from("rh_payroll_periods").insert({competence,status:"aberta"}).select("*").single()).data;if(!period)throw new Error("Não foi possível abrir a competência.");
  await supabaseAdmin.from("rh_audit_log").insert({actor_user_id:actor.id,action:"FOLHA_COMPETENCIA_ABERTA",entity_type:"rh_payroll_periods",entity_id:period.id,after_data:period});return period;
});

export const calculateRhPayroll=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:{period_id:string})=>{if(!input?.period_id)throw new Error("Competência inválida.");return input;}).handler(async({context,data})=>{
  const actor=await requireRhOperator(context);
  const {data:period,error:pe}=await supabaseAdmin.from("rh_payroll_periods").select("*").eq("id",data.period_id).maybeSingle();
  if(pe)throw new Error(pe.message); if(!period)throw new Error("Competência não encontrada.");
  if(period.status==="fechada")throw new Error("Folha fechada não pode ser recalculada.");
  const competence=String(period.competence).slice(0,7);
  if(competence!=="2026-01"&&competence<"2026-01")throw new Error("O motor fiscal parametrizado desta versão está homologado para competências a partir de 01/2026.");
  const {data:employees,error:ee}=await supabaseAdmin.from("rh_employees").select("id,full_name,registration_data").eq("is_active",true);
  if(ee)throw new Error(ee.message);
  const ids=(employees??[]).map((e:any)=>e.id);
  const [{data:contracts,error:ce},{data:dependents,error:de}]=await Promise.all([
    ids.length?supabaseAdmin.from("rh_employee_contracts").select("employee_id,salary_cents,contract_type").in("employee_id",ids).eq("is_current",true):Promise.resolve({data:[],error:null}),
    ids.length?supabaseAdmin.from("rh_employee_dependents").select("employee_id,id").in("employee_id",ids).eq("is_active",true).eq("is_ir_dependent",true):Promise.resolve({data:[],error:null})
  ]);
  if(ce)throw new Error(ce.message);if(de)throw new Error(de.message);
  const cmap=new Map((contracts??[]).map((x:any)=>[x.employee_id,{salary:Number(x.salary_cents??0),type:x.contract_type??"CLT"}]));
  const depMap=new Map<string,number>();for(const d of dependents??[])depMap.set(d.employee_id,(depMap.get(d.employee_id)??0)+1);
  const calcInss=(gross:number)=>{const bands=[[162100,0.075],[290284,0.09],[435427,0.12],[847555,0.14]];let base=Math.min(gross,847555);let prev=0;let total=0;for(const [limit,rate] of bands){const slice=Math.max(0,Math.min(base,limit)-prev);total+=slice*rate;prev=limit;if(base<=limit)break;}return Math.round(total);};
  const calcIrrf=(gross:number,inss:number,deps:number)=>{const legalBase=Math.max(0,gross-inss-deps*18959);const simplifiedBase=Math.max(0,gross-60720);const base=Math.min(legalBase,simplifiedBase);let tax=0;if(base>466468)tax=base*0.275-90873;else if(base>375105)tax=base*0.225-67549;else if(base>282665)tax=base*0.15-39416;else if(base>242880)tax=base*0.075-18216;tax=Math.max(0,Math.round(tax));let reduction=0;if(gross<=500000)reduction=Math.min(tax,31289);else if(gross<=735000)reduction=Math.min(tax,Math.max(0,Math.round(97862-0.133145*gross)));return Math.max(0,tax-reduction);};
  const runs=(employees??[]).map((e:any)=>{const contract=cmap.get(e.id);const gross=contract?.salary||moneyToCents(e.registration_data?.salary);const inss=calcInss(gross);const irrf=calcIrrf(gross,inss,depMap.get(e.id)??0);const fgts=contract?.type==="APRENDIZ"?Math.round(gross*.02):Math.round(gross*.08);return {period_id:period.id,employee_id:e.id,gross_cents:gross,discount_cents:inss+irrf,net_cents:Math.max(0,gross-inss-irrf),inss_base_cents:Math.min(gross,847555),irrf_base_cents:Math.max(0,gross-inss-(depMap.get(e.id)??0)*18959),fgts_base_cents:fgts,status:"calculada",_inss:inss,_irrf:irrf,_fgts:fgts};});
  for(const run of runs){
    const clean={period_id:run.period_id,employee_id:run.employee_id,gross_cents:run.gross_cents,discount_cents:run.discount_cents,net_cents:run.net_cents,inss_base_cents:run.inss_base_cents,irrf_base_cents:run.irrf_base_cents,fgts_base_cents:run.fgts_base_cents,status:run.status};
    const {data:saved,error:re}=await supabaseAdmin.from("rh_payroll_runs").upsert(clean,{onConflict:"period_id,employee_id"}).select("*").single();if(re)throw new Error(re.message);
    const items=[["provento","SALARIO","Salário base",run.gross_cents],["desconto","INSS","INSS empregado",run._inss],["desconto","IRRF","IRRF",run._irrf],["encargo","FGTS","FGTS patronal",run._fgts]];
    for(const [item_type,code,description,amount_cents] of items){const payload={item_type,description,quantity:1,rate:item_type==="encargo"?(run._fgts===Math.round(run.gross_cents*.02)?2:8):100,amount_cents,reference:{source:"motor_folha_2026",run_id:saved.id}};const {data:existing,error:xe}=await supabaseAdmin.from("rh_payroll_items").select("id").eq("period_id",period.id).eq("employee_id",run.employee_id).eq("code",code).limit(1);if(xe)throw new Error(xe.message);if(existing?.[0]){const {error:ie}=await supabaseAdmin.from("rh_payroll_items").update(payload).eq("id",existing[0].id);if(ie)throw new Error(ie.message);}else{const {error:ie}=await supabaseAdmin.from("rh_payroll_items").insert({period_id:period.id,employee_id:run.employee_id,code,...payload});if(ie)throw new Error(ie.message);}}
  }
  const {data:updated,error:ue}=await supabaseAdmin.from("rh_payroll_periods").update({status:"calculada",updated_at:new Date().toISOString()}).eq("id",period.id).select("*").single();if(ue)throw new Error(ue.message);
  await supabaseAdmin.from("rh_audit_log").insert({actor_user_id:actor.id,action:"FOLHA_CALCULADA",entity_type:"rh_payroll_periods",entity_id:period.id,after_data:{employees:runs.length,competence,motor:"2026",rules:["INSS","IRRF","FGTS"]}});
  return {period:updated,employees:runs.length};
});
export const closeRhPayrollPeriod=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:{period_id:string})=>{if(!input?.period_id)throw new Error("Competência inválida.");return input;}).handler(async({context,data})=>{
  const actor=await requireRhOperator(context);const {data:period,error}=await supabaseAdmin.from("rh_payroll_periods").update({status:"fechada",closed_at:new Date().toISOString(),approved_at:new Date().toISOString(),approved_by:actor.id,updated_at:new Date().toISOString()}).eq("id",data.period_id).neq("status","fechada").select("*").maybeSingle();if(error)throw new Error(error.message);if(!period)throw new Error("Folha não encontrada ou já fechada.");await supabaseAdmin.from("rh_audit_log").insert({actor_user_id:actor.id,action:"FOLHA_FECHADA",entity_type:"rh_payroll_periods",entity_id:period.id,after_data:period});return period;
});

export const listRhPayroll=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{await requireRhOperator(context);const {data,error}=await supabaseAdmin.from("rh_payroll_periods").select("*,rh_payroll_runs(*)").order("competence",{ascending:false});if(error)throw new Error(error.message);return data??[];});

export const createRhVacationRequest=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:{employee_id:string;start_date:string;end_date:string;days:number;vacation_period_id?:string;notes?:string})=>{if(!input?.employee_id||!input.start_date||!input.end_date||!input.days)throw new Error("Preencha funcionário, período e dias.");return input;}).handler(async({context,data})=>{const actor=await requireRhOperator(context);const {data:row,error}=await supabaseAdmin.from("rh_vacation_requests").insert({...data,status:"solicitada"}).select("*").single();if(error)throw new Error(error.message);await supabaseAdmin.from("rh_audit_log").insert({actor_user_id:actor.id,employee_id:data.employee_id,action:"FERIAS_SOLICITADAS",entity_type:"rh_vacation_requests",entity_id:row.id,after_data:row});return row;});
export const updateRhVacationRequest=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:{id:string;status:"aprovada"|"reprovada"|"cancelada";notes?:string})=>{if(!input?.id)throw new Error("Solicitação inválida.");return input;}).handler(async({context,data})=>{const actor=await requireRhOperator(context);const payload:any={status:data.status,notes:data.notes??null};if(data.status==="aprovada"){payload.approved_at=new Date().toISOString();payload.approved_by=actor.id;}const {data:row,error}=await supabaseAdmin.from("rh_vacation_requests").update(payload).eq("id",data.id).select("*").single();if(error)throw new Error(error.message);await supabaseAdmin.from("rh_audit_log").insert({actor_user_id:actor.id,employee_id:row.employee_id,action:"FERIAS_STATUS_ALTERADO",entity_type:"rh_vacation_requests",entity_id:row.id,after_data:row});return row;});

export const createRhTimeAdjustment=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:{employee_id:string;reference_date:string;adjustment_type:string;minutes:number;reason:string})=>{if(!input?.employee_id||!input.reference_date||!input.reason)throw new Error("Funcionário, data e motivo são obrigatórios.");return input;}).handler(async({context,data})=>{const actor=await requireRhOperator(context);const {data:row,error}=await supabaseAdmin.from("rh_time_adjustments").insert({...data,status:"pendente",requested_by:actor.id}).select("*").single();if(error)throw new Error(error.message);await supabaseAdmin.from("rh_audit_log").insert({actor_user_id:actor.id,employee_id:data.employee_id,action:"AJUSTE_PONTO_SOLICITADO",entity_type:"rh_time_adjustments",entity_id:row.id,after_data:row});return row;});
export const updateRhTimeAdjustment=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:{id:string;status:"aprovado"|"reprovado";minutes?:number})=>{if(!input?.id)throw new Error("Ajuste inválido.");return input;}).handler(async({context,data})=>{const actor=await requireRhOperator(context);const {data:row,error}=await supabaseAdmin.from("rh_time_adjustments").update({status:data.status,minutes:data.minutes??undefined,approved_by:actor.id,approved_at:new Date().toISOString()}).eq("id",data.id).select("*").single();if(error)throw new Error(error.message);await supabaseAdmin.from("rh_audit_log").insert({actor_user_id:actor.id,employee_id:row.employee_id,action:"AJUSTE_PONTO_STATUS_ALTERADO",entity_type:"rh_time_adjustments",entity_id:row.id,after_data:row});return row;});


export const createRhAdmission=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:{employee_id?:string;expected_start?:string;notes?:string})=>input??{}).handler(async({context,data})=>{const actor=await requireRhOperator(context);const {data:row,error}=await supabaseAdmin.from("rh_admission_processes").insert({employee_id:data.employee_id||null,expected_start:data.expected_start||null,notes:data.notes||null,status:"em_andamento"}).select("*").single();if(error)throw new Error(error.message);await supabaseAdmin.from("rh_audit_log").insert({actor_user_id:actor.id,employee_id:data.employee_id||null,action:"ADMISSAO_ABERTA",entity_type:"rh_admission_processes",entity_id:row.id,after_data:row});return row;});

export const createRhTermination=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:{employee_id:string;termination_date:string;reason?:string})=>{if(!input?.employee_id||!input.termination_date)throw new Error("Funcionário e data são obrigatórios.");return input;}).handler(async({context,data})=>{const actor=await requireRhOperator(context);const {data:row,error}=await supabaseAdmin.from("rh_termination_processes").insert({employee_id:data.employee_id,termination_date:data.termination_date,reason:data.reason||null,status:"iniciado"}).select("*").single();if(error)throw new Error(error.message);await supabaseAdmin.from("rh_audit_log").insert({actor_user_id:actor.id,employee_id:data.employee_id,action:"DESLIGAMENTO_ABERTO",entity_type:"rh_termination_processes",entity_id:row.id,after_data:row});return row;});
export const createRhMedicalExam=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:{employee_id:string;exam_type:string;exam_date:string;valid_until?:string;result?:string;provider?:string;notes?:string})=>{if(!input?.employee_id||!input.exam_type||!input.exam_date)throw new Error("Funcionário, tipo e data são obrigatórios.");return input;}).handler(async({context,data})=>{const actor=await requireRhOperator(context);const {data:row,error}=await supabaseAdmin.from("rh_medical_exams").insert({...data}).select("*").single();if(error)throw new Error(error.message);await supabaseAdmin.from("rh_audit_log").insert({actor_user_id:actor.id,employee_id:data.employee_id,action:"EXAME_SST_CRIADO",entity_type:"rh_medical_exams",entity_id:row.id,after_data:row});return row;});

export const createRhEmployeeRequest=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:{employee_id:string;request_type:string;payload?:Record<string,unknown>})=>{if(!input?.employee_id||!input.request_type)throw new Error("Solicitação inválida.");return input;}).handler(async({context,data})=>{const actor=await requireRhOperator(context);const {data:row,error}=await supabaseAdmin.from("rh_employee_requests").insert({employee_id:data.employee_id,request_type:data.request_type,payload:data.payload||{},status:"aberta"}).select("*").single();if(error)throw new Error(error.message);await supabaseAdmin.from("rh_audit_log").insert({actor_user_id:actor.id,employee_id:data.employee_id,action:"SOLICITACAO_COLABORADOR_CRIADA",entity_type:"rh_employee_requests",entity_id:row.id,after_data:row});return row;});
export const resolveRhEmployeeRequest=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:{id:string;status:"em_analise"|"resolvida"|"cancelada"})=>{if(!input?.id)throw new Error("Solicitação inválida.");return input;}).handler(async({context,data})=>{const actor=await requireRhOperator(context);const final=["resolvida","cancelada"].includes(data.status);const {data:row,error}=await supabaseAdmin.from("rh_employee_requests").update({status:data.status,resolved_at:final?new Date().toISOString():null,resolved_by:final?actor.id:null}).eq("id",data.id).select("*").single();if(error)throw new Error(error.message);await supabaseAdmin.from("rh_audit_log").insert({actor_user_id:actor.id,employee_id:row.employee_id,action:"SOLICITACAO_STATUS_ALTERADO",entity_type:"rh_employee_requests",entity_id:row.id,after_data:row});return row;});
