CREATE TABLE IF NOT EXISTS public.dbs_control_clients (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), legal_name text NOT NULL, trade_name text, cnpj text, logo_storage_path text, phone text, email text, notes text, status text NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo','inativo')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.dbs_control_sites (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), client_id uuid NOT NULL REFERENCES public.dbs_control_clients(id) ON DELETE RESTRICT, name text NOT NULL, address_json jsonb NOT NULL DEFAULT '{}'::jsonb, contact_name text, contact_phone text, contact_email text, notes text, status text NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo','inativo')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.dbs_control_equipment (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), client_id uuid NOT NULL REFERENCES public.dbs_control_clients(id) ON DELETE RESTRICT, site_id uuid REFERENCES public.dbs_control_sites(id) ON DELETE RESTRICT, tag_code text, equipment_type text, brand text, model text, serial_number text, capacity text, environment text, installation_date date, status text NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo','inativo','baixado')), technical_notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.dbs_control_service_catalog (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, description text, estimated_hours numeric(8,2), table_value_cents integer, status text NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo','inativo')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.dbs_control_parts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), sku text UNIQUE, name text NOT NULL, description text, stock_quantity numeric(12,3) NOT NULL DEFAULT 0, cost_cents integer, sale_cents integer, status text NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo','inativo')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.dbs_control_work_orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), protocol text UNIQUE NOT NULL, client_id uuid NOT NULL REFERENCES public.dbs_control_clients(id) ON DELETE RESTRICT, site_id uuid REFERENCES public.dbs_control_sites(id) ON DELETE RESTRICT, assigned_employee_id uuid REFERENCES public.rh_employees(id) ON DELETE RESTRICT, created_by_user_id uuid REFERENCES public.users(id) ON DELETE SET NULL, service_id uuid REFERENCES public.dbs_control_service_catalog(id) ON DELETE SET NULL, type text NOT NULL DEFAULT 'corretiva', priority text NOT NULL DEFAULT 'normal', status text NOT NULL DEFAULT 'aberta', scheduled_at timestamptz, started_at timestamptz, completed_at timestamptz, sla_deadline timestamptz, description text, technical_opinion text, observation text, latitude numeric, longitude numeric, signature_name text, signature_data text, total_cents integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.dbs_control_work_order_equipment (work_order_id uuid NOT NULL REFERENCES public.dbs_control_work_orders(id) ON DELETE CASCADE, equipment_id uuid NOT NULL REFERENCES public.dbs_control_equipment(id) ON DELETE RESTRICT, PRIMARY KEY (work_order_id, equipment_id));
CREATE TABLE IF NOT EXISTS public.dbs_control_work_order_parts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), work_order_id uuid NOT NULL REFERENCES public.dbs_control_work_orders(id) ON DELETE CASCADE, part_id uuid NOT NULL REFERENCES public.dbs_control_parts(id) ON DELETE RESTRICT, quantity numeric(12,3) NOT NULL CHECK (quantity > 0), unit_cents integer, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.dbs_control_work_order_services (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), work_order_id uuid NOT NULL REFERENCES public.dbs_control_work_orders(id) ON DELETE CASCADE, service_id uuid REFERENCES public.dbs_control_service_catalog(id) ON DELETE RESTRICT, description text, quantity numeric(12,3) NOT NULL DEFAULT 1 CHECK (quantity > 0), unit_cents integer, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.dbs_control_work_order_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), work_order_id uuid NOT NULL REFERENCES public.dbs_control_work_orders(id) ON DELETE CASCADE, actor_user_id uuid REFERENCES public.users(id) ON DELETE SET NULL, event_type text NOT NULL, old_status text, new_status text, details jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.dbs_control_work_order_attachments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), work_order_id uuid NOT NULL REFERENCES public.dbs_control_work_orders(id) ON DELETE CASCADE, uploaded_by_user_id uuid REFERENCES public.users(id) ON DELETE SET NULL, storage_path text NOT NULL, file_name text NOT NULL, file_type text, attachment_type text NOT NULL DEFAULT 'evidencia', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.dbs_control_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), scope_key text NOT NULL UNIQUE, company_id uuid REFERENCES public.companies(id) ON DELETE CASCADE, owner_user_id uuid REFERENCES public.users(id) ON DELETE SET NULL, state jsonb NOT NULL, state_version integer NOT NULL DEFAULT 2, updated_by uuid REFERENCES public.users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());

CREATE OR REPLACE FUNCTION public.dbs_my_employee_ids() RETURNS SETOF uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT id FROM public.rh_employees WHERE ponto_portal_user_id = public.current_app_user_id() AND ponto_access_enabled AND dbs_control_access_enabled AND is_active $$;
CREATE OR REPLACE FUNCTION public.dbs_my_work_order_ids() RETURNS SETOF uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT id FROM public.dbs_control_work_orders WHERE assigned_employee_id IN (SELECT public.dbs_my_employee_ids()) $$;
REVOKE EXECUTE ON FUNCTION public.dbs_my_employee_ids() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.dbs_my_work_order_ids() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.dbs_my_employee_ids() TO authenticated;
GRANT EXECUTE ON FUNCTION public.dbs_my_work_order_ids() TO authenticated;

DO $$ DECLARE t text; BEGIN
  FOREACH t IN ARRAY ARRAY['dbs_control_clients','dbs_control_sites','dbs_control_equipment','dbs_control_service_catalog','dbs_control_parts','dbs_control_work_orders','dbs_control_work_order_equipment','dbs_control_work_order_parts','dbs_control_work_order_services','dbs_control_work_order_events','dbs_control_work_order_attachments'] LOOP
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO authenticated', t);
    EXECUTE format('GRANT ALL ON public.%I TO service_role', t);
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin())', t || '_admin_all', t);
  END LOOP;
END $$;

CREATE POLICY dbs_os_employee_select ON public.dbs_control_work_orders FOR SELECT TO authenticated USING (assigned_employee_id IN (SELECT public.dbs_my_employee_ids()));
CREATE POLICY dbs_os_employee_update ON public.dbs_control_work_orders FOR UPDATE TO authenticated USING (assigned_employee_id IN (SELECT public.dbs_my_employee_ids())) WITH CHECK (assigned_employee_id IN (SELECT public.dbs_my_employee_ids()));
CREATE POLICY dbs_os_employee_equipment_select ON public.dbs_control_work_order_equipment FOR SELECT TO authenticated USING (work_order_id IN (SELECT public.dbs_my_work_order_ids()));
CREATE POLICY dbs_os_employee_attachments_select ON public.dbs_control_work_order_attachments FOR SELECT TO authenticated USING (work_order_id IN (SELECT public.dbs_my_work_order_ids()));
CREATE POLICY dbs_os_employee_events_select ON public.dbs_control_work_order_events FOR SELECT TO authenticated USING (work_order_id IN (SELECT public.dbs_my_work_order_ids()));
CREATE POLICY dbs_client_employee_select ON public.dbs_control_clients FOR SELECT TO authenticated USING (id IN (SELECT client_id FROM public.dbs_control_work_orders WHERE id IN (SELECT public.dbs_my_work_order_ids())));
CREATE POLICY dbs_site_employee_select ON public.dbs_control_sites FOR SELECT TO authenticated USING (id IN (SELECT site_id FROM public.dbs_control_work_orders WHERE id IN (SELECT public.dbs_my_work_order_ids())));
CREATE POLICY dbs_equipment_employee_select ON public.dbs_control_equipment FOR SELECT TO authenticated USING (id IN (SELECT equipment_id FROM public.dbs_control_work_order_equipment WHERE work_order_id IN (SELECT public.dbs_my_work_order_ids())));
CREATE POLICY dbs_service_employee_select ON public.dbs_control_service_catalog FOR SELECT TO authenticated USING (id IN (SELECT service_id FROM public.dbs_control_work_order_services WHERE work_order_id IN (SELECT public.dbs_my_work_order_ids())));
CREATE POLICY dbs_parts_employee_select ON public.dbs_control_parts FOR SELECT TO authenticated USING (id IN (SELECT part_id FROM public.dbs_control_work_order_parts WHERE work_order_id IN (SELECT public.dbs_my_work_order_ids())));
CREATE POLICY dbs_os_parts_employee_select ON public.dbs_control_work_order_parts FOR SELECT TO authenticated USING (work_order_id IN (SELECT public.dbs_my_work_order_ids()));
CREATE POLICY dbs_os_parts_employee_insert ON public.dbs_control_work_order_parts FOR INSERT TO authenticated WITH CHECK (work_order_id IN (SELECT public.dbs_my_work_order_ids()));
CREATE POLICY dbs_os_services_employee_select ON public.dbs_control_work_order_services FOR SELECT TO authenticated USING (work_order_id IN (SELECT public.dbs_my_work_order_ids()));
CREATE POLICY dbs_os_services_employee_insert ON public.dbs_control_work_order_services FOR INSERT TO authenticated WITH CHECK (work_order_id IN (SELECT public.dbs_my_work_order_ids()));
CREATE POLICY dbs_os_events_employee_insert ON public.dbs_control_work_order_events FOR INSERT TO authenticated WITH CHECK (work_order_id IN (SELECT public.dbs_my_work_order_ids()) AND actor_user_id = public.current_app_user_id());
CREATE POLICY dbs_os_attachments_employee_insert ON public.dbs_control_work_order_attachments FOR INSERT TO authenticated WITH CHECK (work_order_id IN (SELECT public.dbs_my_work_order_ids()) AND uploaded_by_user_id = public.current_app_user_id());

GRANT SELECT, INSERT, UPDATE ON public.dbs_control_snapshots TO authenticated;
GRANT ALL ON public.dbs_control_snapshots TO service_role;
ALTER TABLE public.dbs_control_snapshots ENABLE ROW LEVEL SECURITY;
CREATE POLICY dbs_control_snapshots_select ON public.dbs_control_snapshots FOR SELECT TO authenticated USING (public.current_role_key() = 'SUPER_ADMIN');
CREATE POLICY dbs_control_snapshots_insert ON public.dbs_control_snapshots FOR INSERT TO authenticated WITH CHECK (public.current_role_key() = 'SUPER_ADMIN');
CREATE POLICY dbs_control_snapshots_update ON public.dbs_control_snapshots FOR UPDATE TO authenticated USING (public.current_role_key() = 'SUPER_ADMIN') WITH CHECK (public.current_role_key() = 'SUPER_ADMIN');