import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BriefcaseBusiness, Building2, Clock3, Plus, RefreshCw } from "lucide-react";
import { listRhMasterData, saveRhDepartment, saveRhPosition, saveRhWorkSchedule } from "@/lib/rh.dp.functions";
const input="w-full rounded-xl border border-slate-700 bg-[#0F172A] px-3 py-2.5 text-xs text-slate-100 outline-none focus:border-[#F59E0B]";
const primary="inline-flex items-center justify-center gap-2 rounded-xl bg-[#F59E0B] px-4 py-2.5 text-xs font-black text-slate-950 disabled:opacity-50";
const secondary="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-800 px-4 py-2.5 text-xs font-bold text-slate-200 disabled:opacity-50";
export function RhDpTools(){const qc=useQueryClient();const q=useQuery({queryKey:["rh-master-data"],queryFn:()=>listRhMasterData()});const [tab,setTab]=useState<"departamentos"|"cargos"|"jornadas">("departamentos");const refresh=()=>qc.invalidateQueries({queryKey:["rh-master-data"]});return <section className="rounded-2xl border border-slate-800 bg-[#1E293B] shadow-sm"><div className="border-b border-slate-800 bg-[#0F172A] p-5 sm:p-6"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#F59E0B]">RH · ferramentas administrativas</p><div className="mt-1 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h2 className="text-xl font-black text-slate-50">Estrutura do RH</h2><p className="mt-1 text-xs text-slate-400">Mantenha setores, cargos e jornadas sem duplicar o cadastro de funcionários.</p></div><button onClick={()=>q.refetch()} className={secondary}><RefreshCw className="h-4 w-4"/>Atualizar</button></div></div><div className="flex flex-wrap gap-2 border-b border-slate-800 p-4">{[["departamentos","Departamentos",Building2],["cargos","Cargos",BriefcaseBusiness],["jornadas","Jornadas",Clock3]].map(([k,l,I]:any)=><button key={k} onClick={()=>setTab(k)} className={tab===k?primary:secondary}><I className="h-4 w-4"/>{l}</button>)}</div><div className="p-5 sm:p-6">{q.isLoading?<p className="text-xs text-slate-400">Carregando estrutura…</p>:q.error?<p className="text-xs text-red-300">{q.error instanceof Error?q.error.message:"Erro ao carregar estrutura."}</p>:tab==="departamentos"?<Departments data={q.data?.departments??[]} refresh={refresh}/>:tab==="cargos"?<Positions data={q.data?.positions??[]} refresh={refresh}/>:<Schedules data={q.data?.schedules??[]} refresh={refresh}/>}</div></section>}
function Departments({data,refresh}:{data:any[];refresh:()=>void}){const [name,setName]=useState("");const [code,setCode]=useState("");const m=useMutation({mutationFn:()=>saveRhDepartment({data:{name,code}}),onSuccess:()=>{setName("");setCode("");refresh()}});return <Master title="Departamentos" icon={Building2}><div className="grid gap-2 md:grid-cols-[1fr_180px_auto]"><input className={input} placeholder="Nome do departamento" value={name} onChange={e=>setName(e.target.value)}/><input className={input} placeholder="Código" value={code} onChange={e=>setCode(e.target.value)}/><button className={primary} disabled={!name.trim()||m.isPending} onClick={()=>m.mutate()}><Plus className="h-4 w-4"/>Adicionar</button></div><List items={data}/></Master>}
function Positions({data,refresh}:{data:any[];refresh:()=>void}){const [name,setName]=useState("");const [cbo,setCbo]=useState("");const m=useMutation({mutationFn:()=>saveRhPosition({data:{name,cbo}}),onSuccess:()=>{setName("");setCbo("");refresh()}});return <Master title="Cargos e CBO" icon={BriefcaseBusiness}><div className="grid gap-2 md:grid-cols-[1fr_180px_auto]"><input className={input} placeholder="Nome do cargo" value={name} onChange={e=>setName(e.target.value)}/><input className={input} placeholder="CBO (opcional)" value={cbo} onChange={e=>setCbo(e.target.value)}/><button className={primary} disabled={!name.trim()||m.isPending} onClick={()=>m.mutate()}><Plus className="h-4 w-4"/>Adicionar</button></div><List items={data} extra="cbo"/></Master>}
function Schedules({data,refresh}:{data:any[];refresh:()=>void}){const [name,setName]=useState("");const [hours,setHours]=useState("44");const [breaks,setBreaks]=useState("60");const [tol,setTol]=useState("5");const m=useMutation({mutationFn:()=>saveRhWorkSchedule({data:{name,weekly_hours:Number(hours),break_minutes:Number(breaks),tolerance_minutes:Number(tol)}}),onSuccess:()=>{setName("");refresh()}});return <Master title="Jornadas de trabalho" icon={Clock3}><div className="grid gap-2 md:grid-cols-4"><input className={input} placeholder="Nome da jornada" value={name} onChange={e=>setName(e.target.value)}/><input className={input} type="number" placeholder="Horas/semana" value={hours} onChange={e=>setHours(e.target.value)}/><input className={input} type="number" placeholder="Intervalo (min)" value={breaks} onChange={e=>setBreaks(e.target.value)}/><div className="flex gap-2"><input className={input} type="number" placeholder="Tolerância" value={tol} onChange={e=>setTol(e.target.value)}/><button className={primary} disabled={!name.trim()||m.isPending} onClick={()=>m.mutate()}><Plus className="h-4 w-4"/>Salvar</button></div></div><List items={data} extra="weekly_hours"/></Master>}
function Master({title,icon:Icon,children}:{title:string;icon:any;children:React.ReactNode}){return <div><div className="mb-4 flex items-center gap-2"><Icon className="h-5 w-5 text-[#F59E0B]"/><div><h3 className="font-black text-slate-50">{title}</h3><p className="text-[11px] text-slate-500">Registros ativos disponíveis para os demais módulos.</p></div></div>{children}</div>}
function List({items,extra}:{items:any[];extra?:string}){return <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{items.map(x=><div key={x.id} className="rounded-xl border border-slate-700 bg-[#141F33] p-3"><p className="text-xs font-bold text-slate-100">{x.name}</p><p className="mt-1 text-[10px] text-slate-500">{extra==="cbo"?(x.cbo?"CBO "+x.cbo:"CBO não informado"):extra==="weekly_hours"?(String(x.weekly_hours??"—")+" h/sem · intervalo "+String(x.break_minutes??0)+" min · tolerância "+String(x.tolerance_minutes??0)+" min"):(x.code||"Sem código")}</p></div>)}{!items.length&&<p className="text-xs text-slate-500">Nenhum registro cadastrado.</p>}</div>}
