/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDbsControlRouteImport } from './routes/_authenticated/dbs-control'
import { Route as AuthenticatedFolhaPontoRouteImport } from './routes/_authenticated/folha-ponto'
import { Route as AuthenticatedPassageRouteImport } from './routes/_authenticated/passage'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedTreasuryRouteImport } from './routes/_authenticated/treasury'
import { Route as AdminRhDashboardRouteImport } from './routes/admin/rh-dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDbsControlRoute = AuthenticatedDbsControlRouteImport.update({
  id: '/dbs-control',
  path: '/dbs-control',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFolhaPontoRoute = AuthenticatedFolhaPontoRouteImport.update({
  id: '/folha-ponto',
  path: '/folha-ponto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPassageRoute = AuthenticatedPassageRouteImport.update({
  id: '/passage',
  path: '/passage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreasuryRoute = AuthenticatedTreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminRhDashboardRoute = AdminRhDashboardRouteImport.update({
  id: '/admin/rh-dashboard',
  path: '/admin/rh-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dbs-control': typeof AuthenticatedDbsControlRoute
  '/folha-ponto': typeof AuthenticatedFolhaPontoRoute
  '/passage': typeof AuthenticatedPassageRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/treasury': typeof AuthenticatedTreasuryRoute
  '/admin/rh-dashboard': typeof AdminRhDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dbs-control': typeof AuthenticatedDbsControlRoute
  '/folha-ponto': typeof AuthenticatedFolhaPontoRoute
  '/passage': typeof AuthenticatedPassageRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/treasury': typeof AuthenticatedTreasuryRoute
  '/admin/rh-dashboard': typeof AdminRhDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dbs-control': typeof AuthenticatedDbsControlRoute
  '/_authenticated/folha-ponto': typeof AuthenticatedFolhaPontoRoute
  '/_authenticated/passage': typeof AuthenticatedPassageRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/treasury': typeof AuthenticatedTreasuryRoute
  '/admin/rh-dashboard': typeof AdminRhDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dbs-control'
    | '/folha-ponto'
    | '/passage'
    | '/portal'
    | '/treasury'
    | '/admin/rh-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/dbs-control'
    | '/folha-ponto'
    | '/passage'
    | '/portal'
    | '/treasury'
    | '/admin/rh-dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/dbs-control'
    | '/_authenticated/folha-ponto'
    | '/_authenticated/passage'
    | '/_authenticated/portal'
    | '/_authenticated/treasury'
    | '/admin/rh-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  AdminRhDashboardRoute: typeof AdminRhDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dbs-control': {
      id: '/_authenticated/dbs-control'
      path: '/dbs-control'
      fullPath: '/dbs-control'
      preLoaderRoute: typeof AuthenticatedDbsControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/folha-ponto': {
      id: '/_authenticated/folha-ponto'
      path: '/folha-ponto'
      fullPath: '/folha-ponto'
      preLoaderRoute: typeof AuthenticatedFolhaPontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passage': {
      id: '/_authenticated/passage'
      path: '/passage'
      fullPath: '/passage'
      preLoaderRoute: typeof AuthenticatedPassageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treasury': {
      id: '/_authenticated/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof AuthenticatedTreasuryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/rh-dashboard': {
      id: '/admin/rh-dashboard'
      path: '/admin/rh-dashboard'
      fullPath: '/admin/rh-dashboard'
      preLoaderRoute: typeof AdminRhDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDbsControlRoute: typeof AuthenticatedDbsControlRoute
  AuthenticatedFolhaPontoRoute: typeof AuthenticatedFolhaPontoRoute
  AuthenticatedPassageRoute: typeof AuthenticatedPassageRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedTreasuryRoute: typeof AuthenticatedTreasuryRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDbsControlRoute: AuthenticatedDbsControlRoute,
  AuthenticatedFolhaPontoRoute: AuthenticatedFolhaPontoRoute,
  AuthenticatedPassageRoute: AuthenticatedPassageRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedTreasuryRoute: AuthenticatedTreasuryRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  AdminRhDashboardRoute: AdminRhDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
