-- DBS AIR · RH/DP operações
-- Aditivo, sem remoção de tabelas ou registros.
CREATE TABLE IF NOT EXISTS public.rh_vacation_periods (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), employee_id uuid NOT NULL REFERENCES public.rh_employees(id) ON DELETE RESTRICT, acquisition_start date NOT NULL, acquisition_end date NOT NULL, concession_deadline date, status text NOT NULL DEFAULT 'aberto', days_earned numeric(6,2) NOT NULL DEFAULT 30, days_used numeric(6,2) NOT NULL DEFAULT 0, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.rh_vacation_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), employee_id uuid NOT NULL REFERENCES public.rh_employees(id) ON DELETE RESTRICT, vacation_period_id uuid REFERENCES public.rh_vacation_periods(id) ON DELETE SET NULL, start_date date NOT NULL, end_date date NOT NULL, days numeric(6,2) NOT NULL, status text NOT NULL DEFAULT 'solicitada', requested_at timestamptz NOT NULL DEFAULT now(), approved_at timestamptz, approved_by uuid REFERENCES public.users(id) ON DELETE SET NULL, notes text);
CREATE TABLE IF NOT EXISTS public.rh_leave_records (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), employee_id uuid NOT NULL REFERENCES public.rh_employees(id) ON DELETE RESTRICT, leave_type text NOT NULL, start_date date NOT NULL, end_date date, status text NOT NULL DEFAULT 'ativo', document_id uuid REFERENCES public.rh_employee_documents(id) ON DELETE SET NULL, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.rh_payroll_periods (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), competence date NOT NULL, status text NOT NULL DEFAULT 'aberta', opened_at timestamptz NOT NULL DEFAULT now(), closed_at timestamptz, approved_at timestamptz, approved_by uuid REFERENCES public.users(id) ON DELETE SET NULL, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS rh_payroll_periods_competence_uq ON public.rh_payroll_periods(competence);
CREATE TABLE IF NOT EXISTS public.rh_payroll_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), period_id uuid NOT NULL REFERENCES public.rh_payroll_periods(id) ON DELETE RESTRICT, employee_id uuid NOT NULL REFERENCES public.rh_employees(id) ON DELETE RESTRICT, item_type text NOT NULL, code text, description text NOT NULL, quantity numeric(12,4), rate numeric(12,6), amount_cents bigint NOT NULL DEFAULT 0, reference jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.rh_payroll_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), period_id uuid NOT NULL REFERENCES public.rh_payroll_periods(id) ON DELETE RESTRICT, employee_id uuid NOT NULL REFERENCES public.rh_employees(id) ON DELETE RESTRICT, gross_cents bigint NOT NULL DEFAULT 0, discount_cents bigint NOT NULL DEFAULT 0, net_cents bigint NOT NULL DEFAULT 0, inss_base_cents bigint NOT NULL DEFAULT 0, irrf_base_cents bigint NOT NULL DEFAULT 0, fgts_base_cents bigint NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'calculada', calculated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(period_id,employee_id));
CREATE TABLE IF NOT EXISTS public.rh_payroll_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text NOT NULL, name text NOT NULL, rule_type text NOT NULL, parameters jsonb NOT NULL DEFAULT '{}'::jsonb, effective_from date NOT NULL, effective_to date, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.rh_time_adjustments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), employee_id uuid NOT NULL REFERENCES public.rh_employees(id) ON DELETE RESTRICT, reference_date date NOT NULL, adjustment_type text NOT NULL, minutes integer NOT NULL DEFAULT 0, reason text NOT NULL, status text NOT NULL DEFAULT 'pendente', requested_by uuid REFERENCES public.users(id) ON DELETE SET NULL, approved_by uuid REFERENCES public.users(id) ON DELETE SET NULL, approved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.rh_time_closures (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), employee_id uuid NOT NULL REFERENCES public.rh_employees(id) ON DELETE RESTRICT, competence date NOT NULL, status text NOT NULL DEFAULT 'aberta', balance_minutes integer NOT NULL DEFAULT 0, overtime_minutes integer NOT NULL DEFAULT 0, missing_minutes integer NOT NULL DEFAULT 0, closed_at timestamptz, closed_by uuid REFERENCES public.users(id) ON DELETE SET NULL, UNIQUE(employee_id,competence));
CREATE TABLE IF NOT EXISTS public.rh_admission_processes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), employee_id uuid REFERENCES public.rh_employees(id) ON DELETE SET NULL, status text NOT NULL DEFAULT 'em_andamento', expected_start date, actual_start date, checklist jsonb NOT NULL DEFAULT '{}'::jsonb, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.rh_termination_processes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), employee_id uuid NOT NULL REFERENCES public.rh_employees(id) ON DELETE RESTRICT, status text NOT NULL DEFAULT 'iniciado', termination_date date, reason text, checklist jsonb NOT NULL DEFAULT '{}'::jsonb, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.rh_medical_exams (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), employee_id uuid NOT NULL REFERENCES public.rh_employees(id) ON DELETE RESTRICT, exam_type text NOT NULL, exam_date date NOT NULL, valid_until date, result text, provider text, document_id uuid REFERENCES public.rh_employee_documents(id) ON DELETE SET NULL, notes text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.rh_safety_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), employee_id uuid NOT NULL REFERENCES public.rh_employees(id) ON DELETE RESTRICT, event_type text NOT NULL, event_date date NOT NULL, status text NOT NULL DEFAULT 'registrado', details jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.rh_employee_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), employee_id uuid NOT NULL REFERENCES public.rh_employees(id) ON DELETE RESTRICT, request_type text NOT NULL, status text NOT NULL DEFAULT 'aberta', payload jsonb NOT NULL DEFAULT '{}'::jsonb, requested_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz, resolved_by uuid REFERENCES public.users(id) ON DELETE SET NULL);
CREATE INDEX IF NOT EXISTS rh_vacation_periods_employee_idx ON public.rh_vacation_periods(employee_id,status);
CREATE INDEX IF NOT EXISTS rh_vacation_requests_employee_idx ON public.rh_vacation_requests(employee_id,start_date DESC);
CREATE INDEX IF NOT EXISTS rh_time_adjustments_employee_idx ON public.rh_time_adjustments(employee_id,reference_date DESC);
CREATE INDEX IF NOT EXISTS rh_medical_exams_employee_idx ON public.rh_medical_exams(employee_id,valid_until);
CREATE INDEX IF NOT EXISTS rh_employee_requests_employee_idx ON public.rh_employee_requests(employee_id,status);
DO $$ DECLARE tbl text; BEGIN FOREACH tbl IN ARRAY ARRAY['rh_vacation_periods','rh_vacation_requests','rh_leave_records','rh_payroll_periods','rh_payroll_items','rh_payroll_runs','rh_payroll_rules','rh_time_adjustments','rh_time_closures','rh_admission_processes','rh_termination_processes','rh_medical_exams','rh_safety_events','rh_employee_requests'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',tbl); EXECUTE format('GRANT ALL ON public.%I TO service_role',tbl); EXECUTE format('REVOKE ALL ON public.%I FROM anon',tbl); END LOOP; END $$;
NOTIFY pgrst,'reload schema';